version: '3.7'
services:
  app:
    image: futures-threadpool:latest
    expose:
      - 8000    # for connecting to debug
      - 9000    # for sending requests to the server
      - 9010    # for connecting with jconsole
    ports:
      - "8000:8000"   
      - "9000:9000"
      - "9010:9010"
    networks:
      - custom-network
    env_file: ./.env
  db:
    image: postgres:14.1
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    networks:
      - custom-network
networks:
  custom-network: {}
